spring:
  datasource:
    url: jdbc:mysql://yourwine.cvhx9cl9iaf8.ap-northeast-2.rds.amazonaws.com:3306/yourwine?serverTimezone=Asia/Seoul
    username: yourwine
    password: yourwineC102
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  devtools: 
    livereload: 
      enabled: true 
    restart:
      enable: true
   