spring:
  datasource:
    url: jdbc:mysql://10.0.3.226:3306/yourwine?serverTimezone=Asia/Seoul
    username: yourwine
    password: yourwineC102
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  devtools: 
    livereload: 
      enabled: true 
    restart:
      enable: true

server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: yourwine
    key-store-type: PKCS12
    key-alias: bns-ssl
  port: 8081